### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by perrymil** [cemordaunt/comethyl#1]
Hi,

I attempted to install comethyl with the instructions given. 

`export R_LIBS=~/Rlibs`
`R`

 `version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"`
`Copyright (C) 2022 The R Foundation for Statistical Computing`
`Platform: x86_64-pc-linux-gnu (64-bit)`

`R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.`

`  Natural language support but running in an English locale`

`R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.`

`Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.`

`> install.packages(c("BiocManager", "remotes"))`

`BiocManager::install("cemordaunt/comethyl")`

`ERROR: dependency ‘genefilter’ is not available for package ‘sva`
`ERROR: dependencies ‘GenomicFeatures’, ‘AnnotationDbi’ are not available for package ‘TxDb.Hsapiens.UCSC.hg38.knownGene’`
`ERROR: dependencies ‘GenomicFeatures’, ‘AnnotationDbi’ are not available for package ‘TxDb.Hsapiens.UCSC.hg19.knownGene’`
`ERROR: dependencies ‘AnnotationDbi’, ‘AnnotationHub’, ‘GenomicFeatures’ are not available for package ‘annotatr’`
`ERROR: dependencies ‘GenomicFeatures’, ‘AnnotationDbi’ are not available for package ‘bumphunter’`
`ERROR: dependencies ‘GenomicFeatures’, ‘GO.db’, ‘AnnotationDbi’, ‘TxDb.Hsapiens.UCSC.hg19.knownGene’,` `‘TxDb.Hsapiens.UCSC.hg38.knownGene’, ‘org.Hs.eg.db’ are not available for package ‘rGREAT’`
`ERROR: dependencies ‘bumphunter’, ‘annotatr’, ‘AnnotationHub’ are not available for package ‘dmrseq’`

`ERROR: dependencies ‘annotatr’, ‘biomaRt’, ‘dmrseq’, ‘GenomicFeatures’, ‘rGREAT’, ‘sva’, ‘WGCNA’ are not available for package ‘comethyl’`

I edited this a bit, but it appears there are some missing dependencies that R doesn't know about where to install them from?

I tried using the install instructions for genefilter:

https://bioconductor.org/packages/release/bioc/html/genefilter.html

`if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")`
    
    `ERROR: dependency ‘png’ is not available for package ‘KEGGREST’`

I was wondering if you were aware of these issues, or possible had any suggestions on resolving this? The host OS is rhel 7.7 (its a cluster head node.)

I was thinking I could try installing the various dependencies via spack, but there are an awful lot of them... anyhew. What OS is this working on? ubuntu? mac? Did I miss something obvious?

**Comment by cemordaunt** [comment]
Hi @perrymil,
This was developed on an ubuntu cluster. You might need to install the dependencies manually if BiocManager::install() isn't finding them automatically.
Best,
Charles
