### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by manoj-hariharan** [cemordaunt/comethyl#2]
Hi Charles,

I was hoping to use comethyl on single cell WGBS methylome datasets (pseudo-bulked). Would that be a reasonable direction?

If so, can you please provide me example input files [an example of the Bismark Cytosine Reports and an example of sample_info.xlsx]? 

We use an in-house pipeline to map the data and generate signal / count files called allC files which we describe here  - https://hq-1.gitbook.io/mc/tech-background/file-formats#allc-file

Thanks,
Manoj.

**Comment by cemordaunt** [comment]
Hi Manoj,

Thanks for your interest! I think it's worth a try to run Comethyl on pseudobulked single cell WGBS, though it hasn't been tested yet.

You can find more info on Comethyl inputs here: [Introduction to Comethyl](https://cemordaunt.github.io/comethyl/articles/comethyl.html#inputs). The Bismark cytosine reports are typically generated by [CpG_Me](https://www.benlaufer.com/CpG_Me/) and are described in the [Bismark docs](http://felixkrueger.github.io/Bismark/bismark/methylation_extraction/). They are assembled for each sample and have the format below:

chromosome | position | strand | count methylated | count unmethylated | C-context | trinucleotide context
chr1	10469	+	0	0	CG	CGC
chr1	10470	-	1	0	CG	CGA
chr1	10471	+	0	0	CG	CGG

The sample trait table should be formatted in your R session as a data.frame with samples in rows and numeric trait values in columns. The sample IDs used in the cytosine report file names should also be included as row names.

Let me know if you have any more questions.

Best,
Charles

**Comment by manoj-hariharan** [comment]
Thanks Charles, I understand the cytosine report format. 
Can you please let me know if the "sample_info.xlsx" mentioned in Comethyl documentation is the input for generating the data.frame in R? It would be great if you can provide the first few lines of the "sample_info.xlsx" file.
Thanks,
Manoj.

**Comment by cemordaunt** [comment]
Yes, that's correct. The sample_info.xlsx should be set up as samples x traits like this:

  | Diagnosis_ASD | MSLelcStandard36 | ga_w | Study_EARLI | percent_cpg_meth_bsseq
-- | -- | -- | -- | -- | --
Sample1 | 1 | 98 | 39 | 1 | 78.5
Sample2 | 0 | 122 | 40.2 | 0 | 78.5
Sample3 | 0 | 125 | 39.1 | 1 | 77.7

Missing values are allowed, but the columns must all be numeric (discrete variables as 1/0). You can then read that excel file into a data.frame:
`colData <- openxlsx::read.xlsx("sample_info.xlsx", rowNames = TRUE)`

Best,
Charles

**Comment by manoj-hariharan** [comment]
Thanks Charles. I'll try it out as you have explained. Appreciate your help!
